<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/coding_act_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Coding act #3

In [28]:
#Python program to inverse and transpose a 3x3 matrix


import numpy as np
A = np.array([[1,-2,3],[4,25,17],[8,9,-10]])
print(A,"\n")

#transposing the matrix

B = np.transpose(A)
print(B)

[[  1  -2   3]
 [  4  25  17]
 [  8   9 -10]] 

[[  1   4   8]
 [ -2  25   9]
 [  3  17 -10]]


In [36]:
#inversing the matrix

B = np.linalg.inv(A) 
print(B)

[[ 0.32317562 -0.00561347  0.08740978]
 [-0.14113873  0.02726544  0.00400962]
 [ 0.13151564  0.02004812 -0.02646351]]


In [34]:
#Python program to inverse and transpose a 4x4 matrix
C = np.array([[1,2,3,-4],[4,5,-6,7],[8,9,-10,11],[12,13,14,-15]])
print(C,"\n")

#tansposing the matrix
D = np.transpose(C)
print(D,"\n")


#inversing the matrix
invC = np.linalg.inv(C)
print(invC)

[[  1   2   3  -4]
 [  4   5  -6   7]
 [  8   9 -10  11]
 [ 12  13  14 -15]] 

[[  1   4   8  12]
 [  2   5   9  13]
 [  3  -6 -10  14]
 [ -4   7  11 -15]] 

[[-0.59090909 -1.125       0.625       0.09090909]
 [ 0.54545455  1.         -0.5        -0.04545455]
 [-0.68181818  1.375      -0.875       0.18181818]
 [-0.63636364  1.25       -0.75        0.13636364]]
