<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from numpy.linalg import eig

A = np.array([[-5,3],[8,6]])
print(A)

inv_A = np.linalg.inv(A)
print(inv_A)

B=np.array([[0],[0]])
print(B)

X=np.dot(inv_A,B)
print(X)


[[-5  3]
 [ 8  6]]
[[-0.11111111  0.05555556]
 [ 0.14814815  0.09259259]]
[[0]
 [0]]
[[0.]
 [0.]]


In [4]:
#Example 1
A=np.array([[-3,8],[4,9]])
print(A)

w,v=np.linalg.eig(A)
print("The eigenvalue/s is/are",w)
print("The eigenvector/s is/are",v)

[[-3  8]
 [ 4  9]]
The eigenvalue/s is/are [-5.24621125 11.24621125]
The eigenvector/s is/are [[-0.96276969 -0.48963374]
 [ 0.27032301 -0.87192821]]


In [5]:
#Example 2
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvalue/s is/are:",w.round())
print("The eigenvector/s is/are:",v.round())

x=np.dot(A,v.round())
print(x)

X=np.array([[-1],[1],[-0]])
Y=np.array([[-1],[1],[-1]])
Z=np.array([[-1],[0],[-1]])


d=np.dot(A,X)
print(d)
e=np.dot(A,Y)
print(e)
f=np.dot(A,Z)
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The eigenvalue/s is/are: [16. -1. -0.]
The eigenvector/s is/are: [[-0. -1.  0.]
 [-1. -0. -1.]
 [-1.  1.  0.]]
[[ -5.   2.  -2.]
 [-11.   2.  -5.]
 [-17.   2.  -8.]]
[[1]
 [1]
 [1]]
[[-2]
 [-5]
 [-8]]
[[ -4]
 [-10]
 [-16]]
