<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/final_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np

e1= np.array([[1,1,1],[1,0,4],[0,0,5]]) #declaring matrix1
e2= np.array([[89],[89],[95]]) #declaring matrix2
x= np.linalg.inv(e1).dot(e2) 
print(x) #to print the output

[[13.]
 [57.]
 [19.]]


Problem 2
It is a singular matrix we cannot solve these, we can use the PINV function to  calculate the generalized inverse of a matrix using its singular-value decomposition. np.linalg solve cannot be use because it is singularmatrix whose determinant is zero

In [24]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print (b)

# compute the pseudo inverse of A

Apinv = np.linalg.pinv(A)


x = Apinv.dot(b)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3

In [30]:
from numpy.linalg import eig


A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A,"\n")
w,v = np.linalg.eig(A)


print("The eigenvalue/s is/are:",w.round())
print("The eigenvector/s is/are:",v.round())


[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalue/s is/are: [-1.  3.  2.]
The eigenvector/s is/are: [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
