<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

# Creating the matrix
A = np.array([[1,1,1],[1,2,2],[1,2,3]])
B = np.array([5,6,8])
print(A)
print(B)



# Solving for inverse of A
A_inv = np.linalg.inv(A)
print(A_inv)

# Solving for BA^-1
X = np.dot(A_inv, B)
print(X)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[5 6 8]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[ 4. -1.  2.]
