<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/midterm_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
a = (5,5)  
b = np.zeros(s)
print("\nMatrix a is \n", b)


Matrix a is 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Question 2

In [55]:
A = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A)

[[1 2 3]
 [0 5 6]
 [0 0 9]
 [0 0 0]]


Question 3

In [49]:
a = np.array([[11,34,24,12,11],[42,32,56,74,74],[11,13,15,16,17],[12,53,36,74,85],[12,42,19,91,83]])

#Print a square matrix which symmetrical
print(a)

[[11 34 24 12 11]
 [42 32 56 74 74]
 [11 13 15 16 17]
 [12 53 36 74 85]
 [12 42 19 91 83]]


Question 4

In [46]:
A = np.array ([[1,2,3],[4,5,-6],[7,8,9]])

invC = np.linalg.inv(A) #Inverse of Matrix C

print(invC)


[[-1.29166667 -0.08333333  0.375     ]
 [ 1.08333333  0.16666667 -0.25      ]
 [ 0.04166667 -0.08333333  0.04166667]]


Question 5

In [57]:
A = np.array ([[1,2,3],[2,3,3],[3,4,-2]])

detofA = np.linalg.det(A)
print("Determinant is =  ",int(detofA))


Determinant is =   5


Question 6

In [58]:
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
B = np.array([[3.4],[8.8],[19.2]])
x = np.linalg.solve(A, B)
print(x)

[[0.2]
 [0.4]
 [0.8]]
