<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/Prelim_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1.

In [32]:
import numpy as np

# creating 4 x 4 matrix
c = np.zeros((4,4))
# filling matrix's diagonal with the value of 1
np.fill_diagonal(c,1)
# printing the output
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 2.

In [31]:
# solution that doubles all the values of each elemen
array = np.multiply(2,c)

#printing the output
print(array)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question 3

In [28]:
# find the cross product of matrices

A = np.array([2,7,4])
B = np.array([3,9,8])


# compute the cross product

product = np.cross(A,B)
print(product)

[20 -4 -3]
