<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np


In [16]:
# addition and subtraction of matrices
a = np.array([[-5,0],[4,1]]) 
b = np.array([[6,-3],[2,3]])
print(a+b)
print(a-b)
print(b-b)

[[ 1 -3]
 [ 6  4]]
[[-11   3]
 [  2  -2]]
[[0 0]
 [0 0]]


sum of matrices 

In [17]:
sum = a+b
print (sum)

[[ 1 -3]
 [ 6  4]]


difference of matrices


In [19]:
# diff 1
diff = a-b
print (diff)

# diff 2
diff = b-b
print (diff)


[[-11   3]
 [  2  -2]]
[[0 0]
 [0 0]]
