<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/python_exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector spaces and its operations




In [2]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print("Vector A is" , A)
print("Vector B is" , B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [13]:
ball1 = np.array([[1,2,3]])
ball2 = np.array([[1,2,3]])
pool = np.array([ball1,ball2])
pool.shape
pool.size
print(pool.shape)
print(pool.size)


(2, 1, 3)
6


In [14]:
R = A+B
print(R)

[ 6 -2]


In [15]:
R = np.add(A,B)
R

array([ 6, -2])

Vector subtraction

In [16]:
R = np.subtract(A,B)
R

array([2, 8])

In [ ]:
##vector scailing

In [17]:
A = np.array([1,5,8,9])
S = 5*A
print(S)

[ 5 25 40 45]


In [18]:
S = np.multiply(5,A)
print(S)

[ 5 25 40 45]


In [28]:
#initialize arrays
A = np.array([2,3,4])
B = np.array([1,7,0])

#compute cross product
output = np.cross(A,B)
print(output)

[-28   4  11]


In [29]:
output = np.dot(A,B) #compute the dot product of A and B
print(output)

23
