<a href="https://colab.research.google.com/github/kyriell2/linear-algebra/blob/main/vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and its operations

In [ ]:
import numpy as np
#Create a 1x3 array
a = np.array ({1,2,3})
print(a)


{1, 2, 3}
[4 5 6]


In [ ]:
#Create a 2 x 3m matrix
b = np.array([[1,2,3],[4,5,6]]) #this is an example of rectangular array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Create a matrix 3x3
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#create a constant array with all values are 6
d = np.full((5,5),6)
print(d)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [ ]:
#create a diagonal matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(a)





[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [ ]:
## Creating a constant array with all values are constant
d =np.full([3,3],8) ## can use []
d_2 =np.full((3,3),0) ## <-- Square Matrix
print(d)
print(d_2)

[[8 8 8]
 [8 8 8]
 [8 8 8]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
## Creating a diagonal matrix
e = np.diagonal(c)
print(c)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [ ]:
## Creating an identity matrix
f = np.eye(6,dtype=int)
print(f)

In [ ]:
## Creating a zero matrix
g = np.zeros((4,8),dtype=int)
print(g)

In [ ]:
## Creating an empty matrix
h = np.empty((0,99))
h_2 = np.empty((5,2)) ## ??????
print(h)
print(h_2)

In [ ]:

## Addition of Matrices
i = np.array([[1,2,3],[4,5,6],[7,8,9]])
j = np.zeros((3,3),dtype=int) ## float + int = float; int + int = int
print(i+j)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
## Subtraction of Matrices
j = np.array([[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]])
print(i-j)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
